import './Clock.scss';
import React, { useMemo } from 'react';
import MiniClock from './MiniClock';
import { Time } from '../types/Time';

interface ClockProps {
    digit?: number
}
function Clock({ digit = 0 }: ClockProps) {

    const miniclocks: Time[][] = useMemo(() => [[
        // Digit 0
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 0, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 1
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: -1, minutes: -1 },
        { hours: 0, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: -1, minutes: -1 },
        { hours: -1, minutes: -1 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: -1, minutes: -1 },
        { hours: -1, minutes: -1 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: -1, minutes: -1 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 3, minutes: 0 },
        { hours: 6, minutes: 45 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 2
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 30 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 3
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 4
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 30 },
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 0, minutes: 30 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: -1, minutes: -1 },
        { hours: -1, minutes: -1 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 30 },
        { hours: -1, minutes: -1 },
        { hours: -1, minutes: -1 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 5
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 3, minutes: 0 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 15 },
        { hours: 0, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 6
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 3, minutes: 0 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 0, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 7
        { hours: 3, minutes: 30 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 0, minutes: 15 },
        { hours: 3, minutes: 45 },
        { hours: 9, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: -1, minutes: -1 },
        { hours: -1, minutes: -1 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: -1, minutes: -1 },
        { hours: -1, minutes: -1 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: -1, minutes: -1 },
        { hours: -1, minutes: -1 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: -1, minutes: -1 },
        { hours: -1, minutes: -1 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 8
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 0, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],
    [
        // Digit 9
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 15 },
        { hours: 6, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 0 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 30 },
        { hours: 0, minutes: 30 },
        { hours: 6, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 0, minutes: 45 },
        { hours: 6, minutes: 0 },
        { hours: 0, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 15 },
        { hours: 9, minutes: 0 },
    ],], []);
    return (
        <div className="clock">
            {miniclocks[digit].map((i, k) => <MiniClock key={k} miniclocks={miniclocks[digit][k]} />)}
        </div>
    )
}

export default Clock;